//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MsnPasswordFinder {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LangRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangRes() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MsnPasswordFinder.LangRes", typeof(LangRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The list has more than one record. You may not want to see&apos;em all. If you think like this press Yes and you can only see selected account&apos;s password..
        /// </summary>
        internal static string EN_Attention {
            get {
                return ResourceManager.GetString("EN_Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy.
        /// </summary>
        internal static string EN_Copy {
            get {
                return ResourceManager.GetString("EN_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy&apos;em All.
        /// </summary>
        internal static string EN_CopyAll {
            get {
                return ResourceManager.GetString("EN_CopyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error occurred while reading cred info..
        /// </summary>
        internal static string EN_Error {
            get {
                return ResourceManager.GetString("EN_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Live Id.
        /// </summary>
        internal static string EN_LiveIdColumn {
            get {
                return ResourceManager.GetString("EN_LiveIdColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Okay.
        /// </summary>
        internal static string EN_Ok {
            get {
                return ResourceManager.GetString("EN_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        internal static string EN_PasswordColumn {
            get {
                return ResourceManager.GetString("EN_PasswordColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PASSWORD NOT SET.
        /// </summary>
        internal static string EN_PwdNotSet {
            get {
                return ResourceManager.GetString("EN_PwdNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please select an item first..
        /// </summary>
        internal static string EN_SelectItemWarn {
            get {
                return ResourceManager.GetString("EN_SelectItemWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Windows Live Messenger Stored Password Recovery.
        /// </summary>
        internal static string EN_Title {
            get {
                return ResourceManager.GetString("EN_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Listede birden fazla kayıt var. Belki hepsini görmek istemeyebilirsiniz. Eğer öyle düşünüyorsanız Evet&apos;i tıklayıp seçtiğiniz hesaba ait parolayı görebilirsiniz..
        /// </summary>
        internal static string TR_Attention {
            get {
                return ResourceManager.GetString("TR_Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kopyala.
        /// </summary>
        internal static string TR_Copy {
            get {
                return ResourceManager.GetString("TR_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hepsini Kopyala.
        /// </summary>
        internal static string TR_CopyAll {
            get {
                return ResourceManager.GetString("TR_CopyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cred bilgilerini okurken bir hata oluştu..
        /// </summary>
        internal static string TR_Error {
            get {
                return ResourceManager.GetString("TR_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Live Kimliği.
        /// </summary>
        internal static string TR_LiveIdColumn {
            get {
                return ResourceManager.GetString("TR_LiveIdColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tamam.
        /// </summary>
        internal static string TR_Ok {
            get {
                return ResourceManager.GetString("TR_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Parola.
        /// </summary>
        internal static string TR_PasswordColumn {
            get {
                return ResourceManager.GetString("TR_PasswordColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PAROLA ATANMAMIŞ.
        /// </summary>
        internal static string TR_PwdNotSet {
            get {
                return ResourceManager.GetString("TR_PwdNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lütfen önce bir eleman seçin..
        /// </summary>
        internal static string TR_SelectItemWarn {
            get {
                return ResourceManager.GetString("TR_SelectItemWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Windows Live Messenger Kayıtlı Parola Kurtarıcısı.
        /// </summary>
        internal static string TR_Title {
            get {
                return ResourceManager.GetString("TR_Title", resourceCulture);
            }
        }
    }
}
